### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by goanpeca** [hanjinliu/napari-filaments#2]
Hi @hanjinliu, in updating the recipe for https://github.com/conda-forge/napari-filaments-feedstock/pull/2 it seems that the dependencies need to be updated/corrected

Found in source code and not listed: 
- importlib_metadata
- macro-kit
- pandas
- psygnal

Listed but not found in source code:
- qtpy

As a general suggestion if a module is directly imported by your code, then it should be added as a dependency, even if that dependency is being provided implicitly by another dependency.

Cheers!

**Comment by hanjinliu** [comment]
Hi @goanpeca ,
sorry for this again, thank you for letting me know!

**Comment by goanpeca** [comment]
Hi @hanjinliu, no worries :), here to help 🚀
